version: "3.8"

services:
  kohya-ss-gui:
    container_name: kohya-ss-gui
    image: kohya-ss-gui:latest
    user: "0:0"
    build:
      context: .
      args:
        - UID=1000
    ports:
      - 7860:7860
      - 6006:6006
    environment:
      SAFETENSORS_FAST_GPU: 1
    tmpfs:
      - /tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./dataset:/dataset
      - ./dataset/images:/app/data
      - ./dataset/logs:/app/logs
      - /root/shiym_proj/diffusers/examples/dreambooth/stable-diffusion-xl-base-1.0:/app/models//stable-diffusion-xl-base-1.0
      - ./dataset/outputs:/app/outputs
      - ./dataset/regularization:/app/regularization
      - ./.cache/config:/app/config
      - ./.cache/user:/home/1000/.cache
      - ./.cache/triton:/home/1000/.triton
      - ./.cache/nv:/home/1000/.nv
      - ./.cache/keras:/home/1000/.keras
      - ./.cache/config:/home/1000/.config # For backward compatibility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['all']
